"""
Pydantic models for laundry monitoring agent structured output.

Defines the response schema for the laundry monitoring agent's structured
output in English and Simplified Chinese. timestamp and image_url are NOT
generated by the model — the Lambda handler injects them after analysis to
save output tokens on every invocation.
"""

from pydantic import BaseModel, Field, field_validator
from typing import Literal


class LaundryAnalysisResponse(BaseModel):
    """
    Single language analysis response for laundry monitoring.
    """

    laundry_detected: bool = Field(
        description="True if laundry or drying racks are visible in open air areas"
    )

    weather_risk_level: Literal["low", "medium", "high"] = Field(
        description="Weather risk for laundry: low, medium, or high"
    )

    weather_summary: str = Field(
        description="Brief summary of current and next hour conditions (max 50 words)",
        max_length=300
    )

    recommendation: Literal["bring_inside", "leave_outside", "no_action"] = Field(
        description="Action recommendation based on risk and detection"
    )

    recommendation_reason: str = Field(
        description="Explanation citing specific weather factors (max 100 words)",
        max_length=600
    )

    notification_title: str = Field(
        description="Actionable push notification title with emoji (max 60 chars)",
        max_length=60
    )

    notification_message: str = Field(
        description="Notification message with weather threat, probability, and laundry location (max 200 chars)",
        max_length=200
    )

    confidence: float = Field(
        description="Analysis confidence 0.0-1.0; lower for poor image quality",
        ge=0.0,
        le=1.0
    )

    @field_validator('confidence')
    @classmethod
    def validate_confidence_range(cls, v: float) -> float:
        """
        Validate that confidence score is within 0.0-1.0 range.

        Args:
            v: Confidence score value

        Returns:
            Validated confidence score

        Raises:
            ValueError: If confidence is outside valid range
        """
        if not 0.0 <= v <= 1.0:
            raise ValueError(f"Confidence score must be between 0.0 and 1.0, got {v}")
        return v


class LocalizedLaundryAnalysisResponse(BaseModel):
    """
    Multi-language response wrapper: complete analysis in both English and
    Simplified Chinese. laundry_detected, weather_risk_level, recommendation,
    and confidence must be identical across both localizations.
    """

    en: LaundryAnalysisResponse = Field(
        description="English localization of the analysis"
    )

    zh_CN: LaundryAnalysisResponse = Field(
        description="Simplified Chinese localization of the analysis"
    )
